### ISSUE TITLE
Purpose of netreq?

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#23]
While debugging the Stretch installation I stumbled upon the "netreq" service which does not work (yet) for Stretch.

What is it good for? It starts under Jessie but seems do nothing because the config is empty.

The CFW seems to provide an app which is not installed via ``tx-pi-setup.sh`` (neither Jessie nor Stretch).

**Comment by heuer** [comment]
> The CFW seems to provide an app which is not installed via `tx-pi-setup.sh` (neither Jessie nor Stretch).

Sorry, it is installed in `/opt/ftc/plugins/`

**Comment by heuer** [comment]
The purpose is a MAC address filter. 

But is the service in use? Both, the CFW and TX-PI seem to configure it wrongly. Both refer to a ``netreq_setup.sh`` but it does not exist.

See
https://github.com/harbaum/tx-pi/blob/a3fe7fbd4f17191d0522d5327973a0ddcc8360a8/setup/tx-pi-setup.sh#L498

Further, I haven't found out where the MAC filter is shown in the GUI.

**Comment by harbaum** [comment]
This is not supposed to do anything on the pi. I'd say tx-pi users know what they do and should not be annoyed by something like this. Just my opinion ...

**Comment by heuer** [comment]
> This is not supposed to do anything on the pi

But it should be installed? 

Unfortunately I don't have a TXT to test, so I am almost clueless why or whether this service is needed or how it is meant to be used.

**Comment by heuer** [comment]
Since it's unclear if this service is useful for TX-Pi, I propose

a) install it but do not enable it by default (a user has to enable it via ``systemctl enable netreq`` explicitely)
b) if nobody claims the missing netreq service: Don't install it at all

**Comment by heuer** [comment]
> b) if nobody claims the missing netreq service: Don't install it at all

Solution for Debian Buster: Do not install it (kept in Stretch, though)
