### ISSUE TITLE
Move Power-Off button to home screen by default?

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#27]
@PeterDHabermehl moved the "Power Off" button within the TX-PI distribution images to the home screen. IMO this is very useful for the TX-PI and I wasn't aware that moving apps is possible (now I've found out how).

Since I think the Power Off app at the home screen is a good idea, I wonder if this shouldn't be done by ``tx-pi-setup.sh`` by default.

What do you think?

**Comment by harbaum** [comment]
That's actually the first thing i usually do. There's one minor disadvantage: Once apps are moved the config file storing app location info is created and further apps installed later are not automatically store in their default categories anymore.

Bascially once you start moving stuff around any auto-categorization is disabled.

**Comment by PeterDHabermehl** [comment]
> Bascially once you start moving stuff around any auto-categorization is disabled.

But why? Could this be changed?
