### ISSUE TITLE
Move tx-pi repository to the ftcommunity?

### ISSUE THREAD

**Issue by harbaum** [ftCommunity/tx-pi#28]
The tx-pi setup started as a personal toy but has become a tool for the entire community.

Github has the ability to move repositories. Would it make sense to move the tx-pi repository to the ftcommunity?

**Comment by PeterDHabermehl** [comment]
I wouldn't expect that to be an advantage. People can already contribute if 
they want to.
But currently there's at least an owner of the repo. Moving it to the 
community just means that in fact no-one would be "responsible" for it any 
longer. 


Am Freitag, 15. März 2019, 15:02:05 CET schrieb Till Harbaum:
> The tx-pi setup started as a personal toy but has become a tool for the
> entire community.
> 
> Github has the ability to move repositories. Would it make sense to move the
> tx-pi repository to the ftcommunity?

**Comment by heuer** [comment]
I have no opinion in one direction or the other. 

What do you expect from a change?

**Comment by harbaum** [comment]
My hope was that people consider this more a community project and are perhaps less hesitant to use it.

**Comment by heuer** [comment]
I buy this argument.

IMO we've nothing to lose. If the move doesn't attract new users or developers, so what?

I'll guess the prevent committers will have an eye on it and contribute code regardless of the project's owner.
