### ISSUE TITLE
Change goo.gl/VXvDML to new repository location

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#30]
The README states:

> wget goo.gl/VXvDML -O tx-pi-setup.sh

The URL refers to the old repository <https://raw.githubusercontent.com/harbaum/tx-pi/master/setup/tx-pi-setup.sh>

Either change the above mentioned shortened URL (if that's possible?!?) or create a new URL which refers to <https://raw.githubusercontent.com/ftCommunity/tx-pi/master/setup/tx-pi-setup.sh>

**Comment by heuer** [comment]
Peter, you seem to be the owner of the shortened URL, see <https://github.com/ftCommunity/tx-pi/commit/056e399afbd30ac9ec08fcfc7947fec1c2c1a700>

I'll assign the issue to you. It's not urgent, though.

**Comment by PeterDHabermehl** [comment]
The goo.gl URL shortening service will cease operation end of Mar. 2019 - I'll try to find an alternate solution.
