### ISSUE TITLE
TouchStyle error during boot

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#35]
```
Traceback (most recent call last):
File "/opt/ftc/TouchStyle.py", line 77, in run
     in_file = open(INPUT_EVENT_DEVICE, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event1'
```

**Comment by PeterDHabermehl** [comment]
You should ask Till about this - I know, we discussed this before, but I forgot the detail.
The behavior is known and was accepted.

**Comment by heuer** [comment]
Without knowing the details I guess that

https://github.com/ftCommunity/ftcommunity-TXT/blob/d9b94f73748efb1b9ea920a0b8468912896f2896/board/fischertechnik/TXT/rootfs/opt/ftc/TouchStyle.py#L15

``TXT = os.path.isfile("/etc/fw-ver.txt")``

should be changed to

``TXT = os.path.isfile("/etc/fw-ver.txt") and not os.path.isfile('/etc/tx-pi')``

**Comment by heuer** [comment]
WIthout knowing the details, I guess that changing
https://github.com/ftCommunity/ftcommunity-TXT/blob/d9b94f73748efb1b9ea920a0b8468912896f2896/board/fischertechnik/TXT/rootfs/opt/ftc/TouchStyle.py#L15

from 

``TXT = os.path.isfile("/etc/fw-ver.txt")``

to

``TXT = os.path.isfile("/etc/fw-ver.txt") and not os.path.isfile('/etc/tx-pi')``

should solve the issue.

Acc. to my understanding, the error is issued by the missing hardware Power button

**Comment by harbaum** [comment]
This is known. On a regular PC it does the same and yes, this relates to the power button.

This never bothered me but feel free to do the necessary changes.

**Comment by heuer** [comment]
Closing this issue since harbaum/TouchUI was updated and TX-Pi uses the version from the repository.
