### ISSUE TITLE
Black screen with LCD35B-V2

### ISSUE THREAD

**Issue by psterk** [ftCommunity/tx-pi#37]
This is a quick workaround for those who have a newer version of the waveshare LCD35B. Version 2 of the Waveshare LCD35B works with the current tx-pi raspian image with tx-pi preinstalled, but the image is not crips as there is a lot of ghosting. When you install the latest waveshare driver specifying LCD35B-show-V2, things initially seem fine, but the display turns black when booting has finished. I downloaded the latest waveshare setup file (git clone https://github.com/waveshare/LCD-show.git) and edited the tx-pi-setup.sh script:

comment out 3 lines:
#wget -N http://www.waveshare.com/w/upload/0/00/LCD-show-170703.tar.gz
#tar xvfz LCD-show-170703.tar.gz
#rm -f ./LCD-show-170703.tar.gz

Change this line:
./$LCD-show $ORIENTATION
to
./$LCD-show-V2 $ORIENTATION

Then run the install script:
sudo tx-pi-setup.sh LCD35B

This will install the LCD35B-V2 files, but as mentioned before, you'll end up with a black screen.  I copied the files waveshare35b-v2.dtbo and waveshare35b-v2-overlay.dtb from /boot/overlays to my laptop using sftp. I then reformatted my SD card, reinstalled the image, booted the raspberry pi, copied the two wavefile files mentioned above to /boot/overlays and finally edited one line in the /boot/config.txt file:

Change:
dtoverlay=waveshare35a:rotate=180
to
dtoverlay=waveshare35b-v2:rotate=180

and reboot. This now works with much sharper images and text. There is probably a better way to do this, but this might help people who like me got stuck. Great project, by the way, keep up the good work.

**Comment by heuer** [comment]
Thanks for your report.

I was aware of Waveshare's Github repository and I tried to use it as default source for installing the display drivers but it contains strange "rotate" definitions which are not compatible to the LCD-show script we use by default.

Anyway, using the Github repository is on my ToDo list and supporting the 3,5" "B" v2 display might be a useful addition we should support.

**Comment by heuer** [comment]
My experiments during the last days with the Waveshare GH repository weren't very successful. 

I implemented a workaround for supporting the Waveshare 3.5" B rev. 2 displays in the develop branch. Unfortunately, I don't own this particular display. Maybe someone (@psterk?) can test the script?

Just follow the install instructions but instead of 
```
wget https://tx-pi.de/tx-pi-setup.sh
```
you should issue 
```
wget https://raw.githubusercontent.com/ftCommunity/tx-pi/develop/setup/tx-pi-setup.sh
```
and
```
sudo bash ./tx-pi-setup.sh LCD35BV2
```
for testing the support for the Waveshare 3.5" B rev. 2 display.

Any feedback is appreciated.

**Comment by psterk** [comment]
Happy to help and I may be able to donate a display - contact me with details how I can get one delivered to you. I'll provide details how I got mine to work. I'm fighting with a work deadline, so you need to be patient for one or two days, but I will follow up. If you could provide me with an email address, that would be helpful.

**Comment by heuer** [comment]
The display arrived today, @psterk. Thank you.

Thanks to your generous donation, I was able to test the setup and found an error.
The bug is fixed in the "develop" branch.

I guess we'll prepare a new release end of next week. In the meantime you can use the (unstable) development branch for 3.5" "B" rev. 2.0 displays:

```
wget https://tx-pi.de/unstable/tx-pi-setup.sh
sudo bash ./tx-pi-setup.sh LCD35BV2
```

**Comment by psterk** [comment]
Glad the display arrived so quickly and that you managed to get it working. I have performed a fresh install on raspian stretch light and I can confirm the new setup script works flawlessly. Thank you for the update.

**Comment by heuer** [comment]
> I have performed a fresh install on raspian stretch light and I can confirm the new setup script works flawlessly.

Thanks for your feedback!
