### ISSUE TITLE
Update libroboint?

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#45]
The TX-Pi setup uses 0.5.3 but 0.5.4 is available:
<https://gitlab.com/Humpelstilzchen/libroboint/-/tags>

Check if the newer version can be used easily.

**Comment by PeterDHabermehl** [comment]
There is no objection against using it. Only major change was support of some new Knobloch devices, which does not bother us in any way.

**Comment by harbaum** [comment]
"new Knobloch devices"? What's that? A TXT successor?

**Comment by heuer** [comment]
Solution: We clone the master branch of https://gitlab.com/Humpelstilzchen/libroboint
See 6306717

Acc. to the developer the master branch should be stable.

**Comment by PeterDHabermehl** [comment]
What's the recent status of libroboint? Have lost trace a little bit...

**Comment by heuer** [comment]
Current state: Unsolved issue. 
Erik tried to solve the issue and we discovered, that a bigger delay here:
<https://gitlab.com/Humpelstilzchen/libroboint/-/blob/master/lib/libroboint.c#L253>
"solves" the problem. If it is set to 2600 it works for Robo LT but not with the Robo IF,
The Robo IF needs a feedback of max. 1 sec. 
Increasing the delay may not a be a solution for Robo LT either, since the controller would run 2,5 sec. without being controlled by an algorithm.

Unfortunately, I don't have a Robo IF so I cannot help to solve the problem. This is a real show stopper for our Buster release.

**Comment by heuer** [comment]
The setup uses the libroboint master branch which works for Pi3.
Will open another issue for the USB problems under Pi4
