### ISSUE TITLE
Update README.md in branch "develop"

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#46]
- [x] Links to "cases/" instead of thingiverse
- [x] Consider two different sections about the hardware setup (Pi3 vs. Pi4)
- [x] Remove information about Jessie
- [x] Add Buster and maybe recommend Buster
- [ ] Remove information about "Disable "wait for network" in the Boot Options"? I guess we already do that? Needs to be checked.
- [ ] Remove section "Tweaking the display performance"? Recommend the Config App?

**Comment by heuer** [comment]
* "Links to cases" fixed with new website
* "Different hardware setup" as well.

**Comment by harbaum** [comment]
I would actually reduce all Readme's to pretty much the bare minimum and reference the new website as much as possible.

**Comment by heuer** [comment]
> I would actually reduce all Readme's to pretty much the bare minimum and reference the new website as much as possible.

Yes, I know. I just kept it open for the "wait for network" tweak. As a reminder for me that I still have to check if this is an issue or not. I guess it is not. I'll close this issue asap.

**Comment by harbaum** [comment]
I've always ignored that recommendation and never had any issues with that.

But the website could indeed use a little 'tips and tricks for the tx pi software setup' page.
