### ISSUE TITLE
Link to case files / STL files

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#50]
Acc. to my observation we don't have a link from tx-pi.de to the cases and / or a page which lists the cases

https://github.com/ftCommunity/tx-pi/tree/master/cases

**Comment by harbaum** [comment]
Indeed. Before doing that I'd like to reorganize the files a little bit with respect to the Raspi4 which needs a different set of cases and upcoming hardware which will also have an impact on this ...

**Comment by heuer** [comment]
> Indeed. Before doing that I'd like to reorganize the files a little bit with respect to the Raspi4 which needs a different set of cases and upcoming hardware which will also have an impact on this ...

Btw, the master branch is outdated, @PeterDHabermehl did some reorganization already here: <https://github.com/ftCommunity/tx-pi/tree/develop/cases> 

Just an idea: Maybe it would be cool if we'd provide a configuration page for the cases. The user specifies which Pi generation he has and which extensions / display etc. and can download all necessary STL files in one zip archive.

**Comment by PeterDHabermehl** [comment]
Well, generally an excellent idea.
But for the moment I think there are more impoartant things to do.
And considering the traffic at the git repo, I don't think you should put too much work into
that at the moment.

Why the heck is this the most accessed file recently?
https://github.com/ftCommunity/tx-pi/blob/develop/cases/CoolerHAT/TX-Pi_CoolerHAT_Spacer.stl[1]



Am Freitag, 8. Mai 2020, 19:15:22 CEST schrieb Lars:
> > Indeed. Before doing that I'd like to reorganize the files a little bit
> > with respect to the Raspi4 which needs a different set of cases and
> > upcoming hardware which will also have an impact on this ...
> Btw, the master branch is outdated, @PeterDHabermehl did some reorganization
> already here: <https://github.com/ftCommunity/tx-pi/tree/develop/cases>
>
> Just an idea: Maybe it would be cool if we'd provide a configuration page
> for the cases. The user specifies which Pi generation he has and which
> extensions / display etc. and can download all necessary STL files in one
> zip archive.



Peter Habermehl
Tel. +49 66 21 / 5 10 40 40
An der Sommerseite 34
Mobil +49 1 79 / 2 23 87 66
36251 Bad Hersfeld
Mail: peter.habermehl@gmx.de


--------
[1] https://github.com/ftCommunity/tx-pi/blob/develop/cases/CoolerHAT/TX-Pi_CoolerHAT_Spacer.stl

**Comment by PeterDHabermehl** [comment]
Well, generally an excellent idea.
But for the moment I think there are more impoartant things to do.
And considering the traffic at the git repo, I don't think you should put too much work into
that at the moment.

Why the heck is this the most accessed file recently?
https://github.com/ftCommunity/tx-pi/blob/develop/cases/CoolerHAT/TX-Pi_CoolerHAT_Spacer.stl[1]

**Comment by harbaum** [comment]
Reorganization is mainly done.

**Comment by heuer** [comment]
Fixed by @harbaum
