### ISSUE TITLE
re-running the install script fails

### ISSUE THREAD

**Issue by PeterDHabermehl** [ftCommunity/tx-pi#56]
just tried to re-run the install script (as I previously did) to update an old stretch setup. Failed due to installation issues with netdev.

What do you think? I would prefer to be able to re-run the script for update purposes. Or do you think there are better ways to keep the setup up to date (not talking about the regular raspbian updates but tx-pi specific stuff)?

**Comment by heuer** [comment]
Re-running the script should be possible. The setup should be idempotent.
What's the exact error? 
IMO the setup script does nothing with systemd.netdev

**Comment by heuer** [comment]
Is this still an issue? Can you provide more information what goes wrong?

**Comment by PeterDHabermehl** [comment]
I will re-check with the new buster setup. IDK what happened then. Will close for now.
