### ISSUE TITLE
SSH problems with SD card images

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#61]
> More info here - SSH is fixed when manually installing
> 
> using the available images SSH access doesn't seem to work correctly, independent of its status in Raspi-config, txpi system 
> config services or the "ssh" file in the boot partition
> However it works after a manual install using the rasbian buster lite image and running the install script.

See https://forum.ftcommunity.de/viewtopic.php?p=48582#p48582

Investigate if there is an issue with the SD card images and SSHd and either confirm and fix or reject this issue.

**Comment by heuer** [comment]
I was able to reproduce the problem with the "TX-Pi (Raspberry Pi 3) with a Waveshare 3.5" type A display" image (https://www.tx-pi.de/images/latest_pi3-35a)

* Download image
* Flash SD card
* Pi boots
* System -> Config -> Services

The SSH server is checked [X] but trying to get a connection to the Pi fails:

```bash
$ ssh -l pi 192.168.172.46 
$ Connection reset by 192.168.172.46 port 22
```

Workaround:
https://forum.ftcommunity.de/viewtopic.php?p=48582#p48633

**Comment by heuer** [comment]
Some or all images contain an incomplete /etc/rc.local file.
The correct rc.local version should create new SSH keys when the device is started the 1st time. 

Easy to fix. Just rerun the scripts to create the dist images, see https://github.com/ftCommunity/tx-pi/blob/develop/dist/README.md

**Comment by harbaum** [comment]
Awesome! Thanks a lot for the quick fix. I am pretty sure there quite some users. I am afraid, most people will just assume it's their own fault if they can't get SSH to work.
