### ISSUE TITLE
Stacking TX-Pi HATs (question)

### ISSUE THREAD

**Issue by MarwanAbdelatti** [ftCommunity/tx-pi#62]
I was thinking of having a raspberry pi similar to the TXT controller. Can I stack two TX-Pi hats on a single raspberry pi so I can get double the inputs, outputs, etc.?

**Comment by heuer** [comment]
No, that's not possible. 
Once a TX-Pi HAT is mounted, the GPIO ports are taken by the HAT and cannot be shared with another TX-Pi HAT. 
It's possible to mount a display, though.

**Comment by heuer** [comment]
A cheap alternative to a TXT controller is a ftDuino which can be connected to the TX-PI and provides more (in fact the same as the TXT controller) I/O ports: http://ftduino.de/en
You can connect the ftDuino either with the USB port or via I2C.

**Comment by MarwanAbdelatti** [comment]
Thanks so much. This is really helpful.
